version: '3.7'
services:
  drupal:
    image: drupal:10.0.0-alpha3-php8.1-apache-bullseye
    ports: 
        - 8080:80
    volumes:
        - drupal-modules:/var/www/html/modules
        - drupal-profiles:/var/www/html/profiles
        - drupal-sites:/var/www/html/themes
        - drupal-themes:/var/www/html/sites
    restart: always

  postgres:
    build:
        context: .
        dockerfile: pg-Dockerfile
    ports:
        - 5432:5432
    environment:
        - POSTGRES_DB=drupal
        - POSTGRES_USER=user
    env_file:
        - proj.env
    restart: always

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: